In [245]:
import numpy as np
from numpy import linalg as LA
import math

In [473]:
m = W #m = next_m

In [476]:
result = np.matmul(m.transpose(), m)

In [477]:
result

array([[1, 0],
       [0, 4]])

In [454]:
m = next_m
d = 1
threshold = 0.0001

In [455]:
x = np.array([[1]\
             ,[1]])

while(d > threshold):
    next_x = np.matmul(m, x) / LA.norm(np.matmul(m, x))
    d = LA.norm(np.subtract(next_x, x))
    x = next_x
    

In [456]:
x

array([[ 9.99999998e-01],
       [-6.10351560e-05]])

In [438]:
x = np.array([[0, 1]
             ,[1, 0]])

In [439]:
y = np.array([[0.70710678],
              [0.70710678]])

In [472]:
U = np.array([[1, 0]
              ,[0, 1/4]])

In [451]:
lamb = np.matmul(x.transpose(), np.matmul(m, x))

In [452]:
lamb

array([[4.]])

In [405]:
eigenvalue = lamb[0][0]
print(eigenvalue)

3.999999999301508


In [406]:
next_m = np.subtract(m, eigenvalue*np.matmul(x, x.transpose()))

In [407]:
next_m

array([[ 9.99999999e-01, -6.10351562e-05],
       [-6.10351562e-05,  1.62981451e-09]])

In [372]:
r = 2
C1 = np.array([[1, 3, 4, 5, 0, 0, 0]])
C2 = np.array([[0, 0, 0, 0, 4, 5, 2]])

C1 = C1 / math.sqrt(r * 51/243)
C2 = C2 / math.sqrt(r * (16+25+4)/243)

C = np.vstack((C1, C2)).transpose()

In [468]:
C

array([[1.54348727, 0.        ],
       [4.6304618 , 0.        ],
       [6.17394907, 0.        ],
       [7.71743633, 0.        ],
       [0.        , 6.57267069],
       [0.        , 8.21583836],
       [0.        , 3.28633535]])

In [463]:
R1 = np.array([[1, 1, 1, 0, 0]])
R2 = np.array([[0, 0, 0, 2, 2]])

R1 = R1 / math.sqrt(r * 3/243)
R2 = R2 / math.sqrt(r * 8/243)

R = np.vstack((R1, R2))

In [471]:
R

array([[6.36396103, 6.36396103, 6.36396103, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 7.79422863, 7.79422863]])

In [442]:
W = np.array([[1, 0]
             ,[0, 2]])

In [478]:
np.matmul(C, np.matmul(np.matmul(U, U), R))

array([[ 9.82269281,  9.82269281,  9.82269281,  0.        ,  0.        ],
       [29.46807844, 29.46807844, 29.46807844,  0.        ,  0.        ],
       [39.29077126, 39.29077126, 39.29077126,  0.        ,  0.        ],
       [49.11346407, 49.11346407, 49.11346407,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  3.20180613,  3.20180613],
       [ 0.        ,  0.        ,  0.        ,  4.00225766,  4.00225766],
       [ 0.        ,  0.        ,  0.        ,  1.60090307,  1.60090307]])

In [459]:
U

array([[1.  , 0.  ],
       [0.  , 0.25]])

In [216]:
next_m = np.subtract(m, eigenvalue*np.matmul(x, np.transpose(x)))

In [217]:
next_m

array([[-2.41984877e-10, -4.63742655e-10, -4.23281410e-10,
        -2.62214250e-10, -3.73096443e-10],
       [-4.63742655e-10, -8.88707784e-10, -8.11174072e-10,
        -5.02509423e-10, -7.14997367e-10],
       [-4.23281410e-10, -8.11174072e-10, -7.40396189e-10,
        -4.58668659e-10, -6.52613963e-10],
       [-2.62214250e-10, -5.02509423e-10, -4.58668659e-10,
        -2.84135382e-10, -4.04282385e-10],
       [-3.73096443e-10, -7.14997367e-10, -6.52613963e-10,
        -4.04282385e-10, -5.75235859e-10]])

In [479]:
result = np.array([[2, 3]
                  ,[3, 10]])

In [486]:
v, w = LA.eig(b)

In [487]:
v

array([ 0.14344504, 34.85655496])

In [488]:
w

array([[-0.77512996, -0.63180182],
       [ 0.63180182, -0.77512996]])

In [483]:
a = np.array([[1, 1]
             ,[2, 2]
             ,[3, 4]])

In [485]:
b= np.matmul(a.transpose(), a)

In [489]:
b

array([[14, 17],
       [17, 21]])